timezone:   America/Los_Angeles
encoding:   UTF-8

exclude:    ["vendor", "Gemfile", "Gemfile.lock", "atlassian-ide-plugin.xml", "README.md"]

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

lsi:         true

redcarpet:
  extensions: []
